### ISSUE TITLE
Markdown compatibility: Bad link translation with parenthetical text

### ISSUE THREAD

**Issue by bmc** [tristanjuricek/knockoff#22]
Consider this Markdown text:

```
Here is a [link][] (cool!)

[link]: http://localhost/
```

With that input, John Gruber's Perl _markdown_ script produces:

```
<p>Here is a <a href="http://localhost/">link</a> (Cool!).</p>
```

Knockoff produces:

```
<p>Here is a [link]<a href="Cool!" ></a>.
</p>
```

Remove the trailing parenthetical expression, and Knockoff produces a valid link:

**Input**

```
Here is a [link][].

[link]: http://localhost/
```

**Output**

```
<p>Here is a <a href="http://localhost/" >link</a>.
</p>
```

Error discovered in: `knockoff_2.8.0.RC2-0.7.1-11.jar`

**Comment by tristanjuricek** [comment]
Should be fixed in 0.7.1-12. Thank you very much for the reproduction example.
