### ISSUE TITLE
code block following a list

### ISSUE THREAD

**Issue by razie** [tristanjuricek/knockoff#30]
this won't work - the code block does not look like a code block

```
1. some item

    code line 1
    code line 2

2. some item
```

**Comment by tristanjuricek** [comment]
That's not a code block, that's a second paragraph in the list by definition: http://daringfireball.net/projects/markdown/syntax#list

(See the "multiple paragraphs" section.)

To get those items into a code block, they'd need another level of indenting.

**Comment by razie** [comment]
Oops - my bad :)

You may be interested to know I just built a wiki site using markdown, using your parser: http://www.racerkidz.com/wiki 

It's working pretty well!

Thank you!
