### ISSUE TITLE
cross publish for scala 2.9.2

### ISSUE THREAD

**Issue by softprops** [tristanjuricek/knockoff#31]
could you do this?

**Comment by tristanjuricek** [comment]
Do you have a requirement to just use the binaries, or could your project leverage sbt's ability to pull and automatically build from github source?

This article worked for me:

http://www.devdaily.com/scala/using-github-projects-scala-library-dependencies-sbt-sbteclipse

The old publishing site was taken down earlier this year, and I haven't quite heard much so I'm assuming that most people are using sbt and not really worrying about it.

Let me know if this doesn't work for you or if you'd like an example app. It was pretty easy for me to just follow the article's instruction and get it to work with 2.9.2...

**Comment by softprops** [comment]
I could definitely use a source dependency for local development but I want to use it as a dependency of a library I intend to publish. I don't think I can do that with it being an unmanaged dependency.

**Comment by philcali** [comment]
@softprops, here's how I currently skirt the issue (I piggy back on binary compatibility), ie:

``` scala
lazy val markdown = Project(
    "lmxml-markdown",
    file("markdown"),
    settings = generalSettings ++ scalaTest ++ Seq(
      libraryDependencies <+= (scalaVersion) {
        case v if v startsWith "2.9" =>
         "com.tristanhunt" % "knockoff_2.9.1" % "0.8.0-16"
        case "2.8.2" =>
         "com.tristanhunt" % "knockoff_2.8.1" % "0.8.0-16"
        case _ =>
         "com.tristanhunt" %% "knockoff" % "0.8.0-16"
      }
    )
  ) dependsOn core
```

When Scala 2.10 becomes final, I hope @tristanjuricek considers publishing his library for that :)

**Comment by softprops** [comment]
thanks @philcali !

**Comment by tristanjuricek** [comment]
OK, I'm going to check out publishing everything through Sonatype, that should be reliable.

**Comment by softprops** [comment]
Thanks @tristanjuricek the oss sonatype repo gets mirrored to maven central which is an sbt default resolver. Having artifacts published there does a good service to everyone in the community because its one less resolver for users to think about. Thanks!

**Comment by tristanjuricek** [comment]
OK, I think the latest version (0.8.0-16) should be up on maven central for generally painless usage.

Thanks for your interest!

**Comment by tristanjuricek** [comment]
I'll note that I've only set it up for the 2.9.x versions of Scala: I could add 2.8.x if there's interest.

**Comment by softprops** [comment]
2.8.2 maybe, though that version will start to wane even more when 2.10 is finally available.

**Comment by philcali** [comment]
+1 ^

I'm more concerned about 2.10
