### ISSUE TITLE
paragraphs mess with html

### ISSUE THREAD

**Issue by razie** [tristanjuricek/knockoff#32]
for instance:

```
    val tabsp = """<table><tr><td>
1

1
</td><td></td></tr></table>"""
println(knockoff(tabsp))
```

results in 

```
ListBuffer(Paragraph(List(HTMLSpan(<table>), HTMLSpan(<tr>), HTMLSpan(<td>), Text(
1
)),1.1), Paragraph(List(Text(1
</td>), HTMLSpan(<td></td>), Text(</tr></table>)),4.1))
```

Note that the closing /tr and /table are rendered as text.

This does not hapen if the 1s are not separated by empty line...

**Comment by razie** [comment]
read the markdown spec again and aparently we're not supposed to re-format the contents of a `<table><td>`' tag - I do like the fact that you are formatting it though...

**Comment by tristanjuricek** [comment]
If you test with the markdown dingus, it doesn't really handle newlines at all very well: http://daringfireball.net/projects/markdown/dingus

I'm going to see what it might mean to include newlines; if it doesn't really cause any other problems, I might try to handle it.

**Comment by tristanjuricek** [comment]
Screw it. It might be slow, but I added HTML blocks to 0.8.1.
