### ISSUE TITLE
Parsing inside blockquote is not always correct

### ISSUE THREAD

**Issue by aquamatthias** [tristanjuricek/knockoff#34]
Hi,

thanks for a great library!
I stumbled about an issue in blockquote parsing, which looks like a parser error:
Following example work just fine:

```
> # Hi
> * One
> * Two
> * Three
```

But this won't work as expected:

```
> Hi
> # Hi
> * One
> * Two
> * Three
```

and produces following html

``` html
<blockquote><p>Hi
# Hi
<em> One
</em> Two
* Three</p></blockquote>
```

Here is the snippet to reproduce this:

``` scala
    import DefaultDiscounter._
    println(toXHTML(knockoff("> # Hi\n> * One\n> * Two\n> * Three")))
    println(toXHTML(knockoff("> Hi\n> # Hi\n> * One\n> * Two\n> * Three")))
```

Best regards,
Matthias

**Comment by tristanjuricek** [comment]
Ah, thanks for the reproduction case!
